# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16.xci
# IP: The module: 'fifo_256x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16/fifo_256x16_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16/fifo_256x16.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16.xci
# IP: The module: 'fifo_256x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16/fifo_256x16_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16/fifo_256x16.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_256x16/fifo_256x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
