# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.srcs/sources_1/ip/fifo_96x512/fifo_96x512.xci
# IP: The module: 'fifo_96x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.srcs/sources_1/ip/fifo_96x512/fifo_96x512/fifo_96x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_96x512'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.srcs/sources_1/ip/fifo_96x512/fifo_96x512/fifo_96x512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_96x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.srcs/sources_1/ip/fifo_96x512/fifo_96x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_96x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.srcs/sources_1/ip/fifo_96x512/fifo_96x512.xci
# IP: The module: 'fifo_96x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.srcs/sources_1/ip/fifo_96x512/fifo_96x512/fifo_96x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_96x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.srcs/sources_1/ip/fifo_96x512/fifo_96x512/fifo_96x512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_96x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.srcs/sources_1/ip/fifo_96x512/fifo_96x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_96x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
