webtalk_init -webtalk_dir C:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.sim/sim_1/behav/xsim.dir/l2p_dma_bench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 06 13:42:25 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0259d854-6ad1-4903-8132-e9289ed4e879" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "065b24f1651e4cfdbcb9bd0f289efcec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2694 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "19" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "410 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "59 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "2543" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1162" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "39" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.67_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "94152_KB" -context "xsim\\usage"
webtalk_transmit -clientid 319132978 -regid "" -xml C:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.sim/sim_1/behav/xsim.dir/l2p_dma_bench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.sim/sim_1/behav/xsim.dir/l2p_dma_bench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/cygwin64/home/saute/yarr_sim/project_sim/project_sim.sim/sim_1/behav/xsim.dir/l2p_dma_bench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
