# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32.xci
# IP: The module: 'fifo_605x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32/fifo_605x32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_605x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32/fifo_605x32.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_605x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_605x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32.xci
# IP: The module: 'fifo_605x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32/fifo_605x32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_605x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32/fifo_605x32.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_605x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/Yarr-fw/ip-cores/kintex7/fifo_605x32/fifo_605x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_605x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
